baseURL = "/"
theme = "dot-hugo-documentation-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = "zh"

[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # 中文
  [Languages.zh]
  languageName = "中文"
  weight = 1
  languageCode = "zh-cn"
  title = "极数科技官网"
  dateFormat = "2006-01-02"
  home = "首页"
  homeURL = "/"
  logo = "极数科技"
  copyright = "本站所有权归 @极数科技 所有"
  
    # 导航栏
    [Languages.zh.menu]
    
      [[Languages.zh.menu.main]]
        weight = 1
        name = "产品中心"
        hasChildren = true

          [[Languages.zh.menu.main]]
            parent = "产品中心"
            name = "极速版"
            URL = "/showcase/supernumV1"
            weight = 1
  
          [[Languages.zh.menu.main]]
            parent = "产品中心"
            name = "会员版"
            URL = "/showcase/supernumV2"
            weight = 2
  
          [[Languages.zh.menu.main]]
            parent = "产品中心"
            name = "高级定制"
            URL = "/showcase/supernumV3"
            weight = 3
            

      [[Languages.zh.menu.main]]
        weight = 3
        name = "常见问题"
        url = "/faq"
        
      [[Languages.zh.menu.main]]
        weight = 4
        name = "联系我们"
        url = "/contact"
        
      [[Languages.zh.menu.main]]
        weight = 5
        name = "其它"
        hasChildren = true
        
          [[Languages.zh.menu.main]]
            parent = "其它"
            name = "安装与配置"
            URL = "/installation"
            weight = 1
            
          [[Languages.zh.menu.main]]
            parent = "其它"
            name = "管理员手册"
            URL = "/maintenance"
            weight = 2

          [[Languages.zh.menu.main]]
            parent = "其它"
            name = "实用技巧"
            URL = "/tips"
            weight = 3



    # banner
    [Languages.zh.params.banner]
      title = "帮助与支持中心"
      description = "与我们一起寻找快速搭建报表平台、报表可视化展示和数据分析的最佳解决方案"
      placeholder = "请输入关键字或文章标题"

    # Topics
    [Languages.zh.params.topics]
      title = "深入了解"
    
    # call to action
    [Languages.zh.params.cta]
      enable = true
      title = "立即与我们展开合作"
      description = "如果您想要与我们展开合作，或者您仍有任何疑问，欢迎留言给我们，当然您也可以直接发送邮件至我们的官邮。"
      btnText = "联系我们"
      btnURL = "/contact"

    # contact
    [Languages.zh.params.contact]
      title = "欢迎留言给我们"
      content = "留下您的联系方式，我们将在第一时间与您取得联系。"
      name = "您的名称"
      email = "您的联系方式"
      message = "留言内容"
      send = "发送"

    # footer social icon
    [[Languages.zh.socialIcon]]
      icon = "fa-tv"
      URL = "/showcase"
      
    [[Languages.zh.socialIcon]]
      icon = "fa-envelope"
      URL = "/contact"
      
    [[Languages.zh.socialIcon]]
      icon = "fa-question"
      URL = "/faq"





  # English Language
  [Languages.en]
  languageName = "English"
  weight = 2
  languageCode = "en-us"
  title = "supernum"
  dateFormat = "2 January 2006"
  home = "Home"
  homeURL = "/en"
  logo = "supernum"
  copyright = "copyrights belong to ©supernum."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 1
        name = "products"
        hasChildren = true

          [[Languages.en.menu.main]]
            parent = "products"
            name = "Primary Edition"
            URL = "/en/showcase/supernumV1"
            weight = 1
  
          [[Languages.en.menu.main]]
            parent = "products"
            name = "Membership Edition"
            URL = "/en/showcase/supernumV2"
            weight = 2
  
          [[Languages.en.menu.main]]
            parent = "products"
            name = "Custom Edition"
            URL = "/en/showcase/supernumV3"
            weight = 3
            

      [[Languages.en.menu.main]]
        weight = 3
        name = "faq"
        url = "/en/faq"
        
      [[Languages.en.menu.main]]
        weight = 4
        name = "contact"
        url = "/en/contact"
        
      [[Languages.en.menu.main]]
        weight = 5
        name = "etc"
        hasChildren = true
        
          [[Languages.en.menu.main]]
            parent = "etc"
            name = "installation"
            URL = "/en/installation"
            weight = 1
            
          [[Languages.en.menu.main]]
            parent = "etc"
            name = "maintenance"
            URL = "/en/maintenance"
            weight = 2

          [[Languages.en.menu.main]]
            parent = "etc"
            name = "tips"
            URL = "/en/tips"
            weight = 3


    # banner
    [Languages.en.params.banner]
      title = "Help and Support Center"
      description = "Follow us to find the best solution to build report platform, present visualize report and manage data"
      image = "image/banner.jpg"
      placeholder = "Please enter keywords or article titles"

    # Topics
    [Languages.en.params.topics]
      title = "Find more"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Cooperate with us now"
      description = "Want to cooperate with us, or still have any questions, please leave a message to us. You can also send mail directly to our official post."
      btnText = "contact us"
      btnURL = "/en/contact"

    # contact
    [Languages.en.params.contact]
      title = "Leave us a message"
      content = "Leave your contact information, we will contact you at the first time."
      name = "Your Name"
      email = "Your Email"
      message = "Message"
      send = "Send"
      
    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "fa-tv"
      URL = "/en/showcase"
      
    [[Languages.en.socialIcon]]
      icon = "fa-envelope"
      URL = "/en/contact"
      
    [[Languages.en.socialIcon]]
      icon = "fa-question"
      URL = "/en/faq"
